# Generated by Django 5.0.7 on 2024-08-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std',
            field=models.CharField(default=12, max_length=40),
            preserve_default=False,
        ),
    ]
