# Generated by Django 5.0.7 on 2024-09-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_std'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='std',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.EmailField(default='m', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.EmailField(default='m', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='m', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.EmailField(default='m', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='m', max_length=40),
        ),
    ]
