# Generated by Django 5.0.7 on 2024-08-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='d_time',
            field=models.TimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='s_date',
            field=models.DateField(blank=True, default='1212', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='s_time',
            field=models.TimeField(blank=True, max_length=100, null=True),
        ),
    ]
