# Generated by Django 5.0.7 on 2024-08-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_course_d_time_course_exam_name_course_s_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='d_time',
            field=models.PositiveIntegerField(blank=True, max_length=100, null=True),
        ),
    ]
