# Generated by Django 5.0.7 on 2024-08-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_course_question_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='std',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
