# Generated by Django 5.0.7 on 2024-09-09 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_question_answer_alter_result_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='std',
        ),
    ]
