# Generated by Django 5.0.7 on 2024-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_course_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(default='journal', max_length=200),
        ),
    ]
