# Generated by Django 5.0.7 on 2024-09-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_question_option4'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ctg',
            field=models.CharField(default='journal', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(max_length=200),
        ),
    ]
