# Generated by Django 5.1 on 2024-09-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_rename_category_percentages_result_ctg'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_mcq',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
